# Generated by Django 2.1.2 on 2018-11-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('reg_date', models.DateTimeField(verbose_name='register_date')),
                ('chng_date', models.DateTimeField(verbose_name='changed_date')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(verbose_name='register_date')),
                ('chng_date', models.DateTimeField(verbose_name='changed_date')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('reg_date', models.DateTimeField(verbose_name='register_date')),
                ('chng_date', models.DateTimeField(verbose_name='changed_date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unknownstation.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(verbose_name='register_date')),
                ('lst_login', models.DateTimeField(verbose_name='latest login time')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unknownstation.User'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unknownstation.User'),
        ),
    ]
