# Generated by Django 2.1.2 on 2018-11-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unknownstation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='unknownstation.Blog'),
            preserve_default=False,
        ),
    ]
