# Generated by Django 2.1.2 on 2018-11-20 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unknownstation', '0002_category_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='chng_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 25299, tzinfo=utc), verbose_name='changed_date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 25299, tzinfo=utc), verbose_name='register_date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='chng_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 25795, tzinfo=utc), verbose_name='changed_date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 25795, tzinfo=utc), verbose_name='register_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chng_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 26291, tzinfo=utc), verbose_name='changed_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 26291, tzinfo=utc), verbose_name='register_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lst_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 24801, tzinfo=utc), verbose_name='latest login time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 20, 12, 11, 5, 24801, tzinfo=utc), verbose_name='register_date'),
        ),
    ]
