# Generated by Django 2.1.2 on 2018-11-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unknownstation', '0003_auto_20181120_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='chng_date',
            field=models.DateTimeField(auto_now=True, verbose_name='changed_date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='register_date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='chng_date',
            field=models.DateTimeField(auto_now=True, verbose_name='changed_date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='register_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='chng_date',
            field=models.DateTimeField(auto_now=True, verbose_name='changed_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='register_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lst_login',
            field=models.DateTimeField(auto_now=True, verbose_name='latest login time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='register_date'),
        ),
    ]
